# Generated by Django 4.0.5 on 2022-06-30 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicines',
            old_name='name',
            new_name='medicine_name',
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
