# Generated by Django 4.0.5 on 2022-07-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_medicines_address_delete_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('working_place', models.CharField(default='', max_length=255)),
                ('professions', models.CharField(default='', max_length=255)),
                ('optional', models.CharField(blank=True, max_length=255)),
                ('review', models.CharField(default='', max_length=255)),
                ('picture_id', models.CharField(default='', max_length=255)),
                ('document_id', models.CharField(default='', max_length=255)),
                ('document_picture_id', models.CharField(default='', max_length=255)),
                ('tel_number', models.CharField(default='', max_length=255)),
                ('tel_auth', models.IntegerField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.cities')),
            ],
        ),
    ]
