# Generated by Django 4.0.5 on 2022-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_botuser_doctor_home_price_doctor_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='status',
            field=models.CharField(default='/start', max_length=255),
        ),
        migrations.AddField(
            model_name='botuser',
            name='status_extra',
            field=models.CharField(default='/start', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='document_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='document_picture_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='picture_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='professions',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='review',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tel_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='working_place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
