# Generated by Django 4.0.5 on 2022-07-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_botuser_status_botuser_status_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default='False'),
        ),
    ]
