# Generated by Django 4.0.5 on 2022-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_doctor_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_status',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
