# Generated by Django 4.0.5 on 2022-07-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_botuser_username_botuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(default='', max_length=255),
        ),
    ]
