# Generated by Django 4.0.5 on 2022-07-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='language',
            field=models.CharField(default='uz', max_length=2),
        ),
    ]
