# Generated by Django 4.0.5 on 2022-07-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_botuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='language',
            field=models.IntegerField(default='0'),
        ),
    ]
