# Generated by Django 4.0.5 on 2022-07-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_botuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='callback_data',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
