# Generated by Django 4.0.5 on 2022-07-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_doctor_city_alter_doctor_doctor_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='tel_auth',
        ),
    ]
