# Generated by Django 4.0.5 on 2022-07-04 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_doctor_tel_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.cities'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
