# Generated by Django 4.0.5 on 2022-07-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_doctor_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='picture',
            new_name='place_id',
        ),
    ]
