# Generated by Django 4.0.5 on 2022-07-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_rename_picture_doctor_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
