# Generated by Django 4.0.5 on 2022-07-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_doctor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='home_price',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
    ]
