# Generated by Django 4.0.5 on 2022-07-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_botuser_previs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='language',
            field=models.CharField(default='', max_length=255),
        ),
    ]
