# Generated by Django 4.0.5 on 2022-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_doctor_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='optional',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
