# Generated by Django 4.0.5 on 2022-07-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_doctor_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='next_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botuser',
            name='next_to_status',
            field=models.IntegerField(default=5),
        ),
    ]
