# Generated by Django 4.0.5 on 2022-07-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_botuser_next_status_botuser_next_to_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='price_time',
            field=models.CharField(default='', max_length=255),
        ),
    ]
