# Generated by Django 4.0.5 on 2022-07-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_doctor_price_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='unique_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
